version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: /app/scripts/installDocker.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: /app/scripts/installApp.sh
      timeout: 300
      runas: ec2-user
