version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: /installDocker.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: /installApp.sh
      timeout: 300
      runas: ec2-user
